### ISSUE TITLE
Some failing tests

### ISSUE THREAD

**Issue by walkerlj0** [saucelabs/my-demo-app-android#7]
Hello!
Still seeing some flaky/ failing tests with release 1.0.3

[See the failures here]( https://github.com/saucelabs/saucectl-espresso-example/runs/4037312201?check_suite_focus=true)

```
1) com.saucelabs.mydemoapp.android.view.activities.DashboardToCheckout.dashboard_Product_Test

	Failure was:
	androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "bod@example.com"' doesn't match the selected view.

2) com.saucelabs.mydemoapp.android.view.activities.LoginTest.succesfulLoginTest

	Failure was:
	androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 539, 1161 and precision: 16, 16' on view 'view.getId() is <2131362266/com.saucelabs.mydemoapp.android:id/passwordET>'.

3) com.saucelabs.mydemoapp.android.view.activities.LoginTest.noPasswordLoginTest

	Failure was:
	androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'an instance of android.widget.TextView and view.getText() with or without transformation to match: is "bod@example.com"' doesn't match the selected view.
Expected: an instance of android.widget.TextView and view.getText() with or without transformation to match: is "bod@example.com"
```

**Comment by diegoperini** [comment]
@walkerlj0 These tests are supposed to pass. Can you share your `saucectl` config so that I can reproduce the failure on my own?

**Comment by diegoperini** [comment]
I'm specifically interested in the device model of the run with failure.

**Comment by FriggaHel** [comment]
👋 
There is some examples here (links are available in the output):
https://github.com/saucelabs/saucectl-espresso-example/pull/14
https://github.com/saucelabs/saucectl-espresso-example/runs/4037312018?check_suite_focus=true

**Comment by diegoperini** [comment]
@walkerlj0 @FriggaHel 

I've just merged a medium sized bugfix PR which hopefully fixes all the problems with tests on mdpi screens.

**Comment by walkerlj0** [comment]
@diegoperini still just one class that keeps consistently failing, I tested on a few different devices and emu:

```
suites:
- name: espresso - Google Pixel 2 .* - Android GoogleAPI Emulator 11.0
  devices:
  - name: Google Pixel 2 .*
  emulators:
  - name: Google Pixel 3a GoogleAPI Emulator
    platformVersions:
    - "11.0"

- name: espresso - Huawei.* – Google Pixel C 8.1
  devices:
  - name: Huawei.*
  emulators:
  - name: Google Pixel C GoogleAPI Emulator
    platformVersions:
    - "8.1"

- name: espresso - *.nexus.* – Android Emulator 6.0
  devices:
  - name: .*nexus.*
  emulators:
  - name: Android Emulator
    platformVersions:
    - "6.0"

artifacts:
  download:
    match:
    - '*'
    when: fail
    directory: artifacts
```
I ran these 3x and it failed each time):

[On Google Pixel C emulator platform version 8.1, the webViewTest() keeps failing](https://app.saucelabs.com/tests/7d02986f8db6483a941365c50e1c8222#6)

[On the Motorola Nesxus on our Real Device cloud, the same webViewTest() also seems to be failing] (https://app.saucelabs.com/tests/bc01cc06ab0e477bae760101e72b872f#6)
